/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#2a6b2c",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "surface-variant": "#dae2fd",
        "on-tertiary-container": "#78da8b",
        "tertiary-fixed-dim": "#79db8d",
        "on-tertiary-fixed-variant": "#005323",
        "on-tertiary-fixed": "#00210a",
        "on-surface": "#131b2e",
        "surface-container-high": "#e2e7ff",
        "outline-variant": "#c0c9bb",
        "tertiary-fixed": "#95f8a7",
        "surface-dim": "#d2d9f4",
        "surface-container-highest": "#dae2fd",
        "on-secondary-fixed": "#331200",
        "primary-fixed-dim": "#91d78a",
        "on-secondary-container": "#682c00",
        "surface": "#faf8ff",
        "outline": "#717a6d",
        "on-background": "#131b2e",
        "primary-container": "#1b5e20",
        "secondary-fixed": "#ffdbca",
        "on-primary-fixed": "#002203",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "error-container": "#ffdad6",
        "on-primary-container": "#90d689",
        "error": "#ba1a1a",
        "secondary-container": "#fd8a42",
        "surface-container-low": "#f2f3ff",
        "secondary": "#9b4500",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#005f29",
        "on-primary": "#ffffff",
        "surface-container": "#eaedff",
        "secondary-fixed-dim": "#ffb68e",
        "primary-fixed": "#acf4a4",
        "on-secondary": "#ffffff",
        "tertiary": "#00451c",
        "inverse-primary": "#91d78a",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#763300",
        "background": "#faf8ff",
        "on-surface-variant": "#41493e",
        "primary": "#00450d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#0c5216"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "space-md": "1rem",
        "margin-desktop": "2rem",
        "space-lg": "1.5rem",
        "gutter": "1rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "margin": "1rem",
        "space-sm": "0.5rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        sans: ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "body-md": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "body-lg": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "title-lg": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "label-lg": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "headline-xl": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "body-bold": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "headline-xl-mobile": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "headline-lg": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "label-md": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"],
        "headline-md": ["'Noto Sans Bengali'", "'Noto Sans'", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "label-lg": ["15px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-bold": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg-mobile": ["22px", { lineHeight: "30px", fontWeight: "700" }],
        "headline-xl-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
